title: Зөв бичигдэв
description: Монгол үгийн алдаа шалгах толь
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
url: "https://zuv.bichig.dev"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
meta:
  yandex-verification: 34a56b64aa11897a
