title: Зөв бичигдэв
description: Монгол үгийн алдаа шалгах толь
remote_theme: bataak/jekyll-rtd-theme
url: "https://zuv.bichig.dev"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
meta:
  yandex-verification: 34a56b64aa11897a
